"""Audit every tracked claim used by the finite-window gap paper.

This is intentionally an invariant checker, not a recomputation of the large
Colab diagonalizations.  Exact artifacts are regenerated byte for byte by
``exact_and_robust_certificates.py --check``; the local and Colab records are
then checked against the theorem-level claims quoted in the manuscript.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


HERE = Path(__file__).resolve().parent


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def load(name: str) -> dict[str, object]:
    return json.loads((HERE / name).read_text(encoding="utf-8"))


def check_exact_artifacts() -> None:
    subprocess.run(
        [sys.executable, str(HERE / "exact_and_robust_certificates.py"), "--check"],
        check=True,
    )
    data = load("certificate_artifacts.json")
    flat = data["exact_flat_extension"]
    require(flat["flat_at_degree_1"], "flat-extension rank test failed")
    require(flat["recovery_exact"], "visible atoms were not recovered exactly")
    require(flat["recovered_visible_atoms"] == ["1/5", "1/2", "4/5"], "wrong atoms")

    hidden = data["finite_noise_hidden_atom"]
    require(hidden["within_componentwise_noise_radius"], "hidden atom left noise ball")
    require(hidden["contaminated_transfer_edge"] == 1.0, "hidden atom did not close gap")
    require(hidden["contaminated_mass_lower_bound"] == 0.0, "hidden mass is nonzero")

    cheb = data["chebyshev_visibility"]
    require(cheb["first_degree_from_analytic_bound"] == 6, "analytic degree changed")
    require(cheb["first_degree_from_robust_visibility_bound"] == 6, "robust visibility degree changed")
    require(cheb["first_degree_with_noise_safe_certificate"] == 5, "noise-safe degree changed")


def check_run(row: dict[str, object], *, large: bool) -> None:
    length = row["L"] if large else row["length"]
    if large:
        require(row["dimension"] == 2**length, f"L={length}: wrong Hilbert dimension")
        require(row["X_overlap_first"] < 1e-20, f"L={length}: X is not parity blind")
        require(row["Z_overlap_first"] > 0.25, f"L={length}: Z lost visibility")
        require(row["block_N6_abs_error"] < 1e-4, f"L={length}: Ritz error too large")
        require(row["block_first_false_gap_witness_degree"] == 1, f"L={length}: block witness moved")
        require(row["X_first_false_gap_witness_degree"] is None, f"L={length}: X unexpectedly witnesses")
        return

    weights = row["probe_overlap_weights"]["rows_are_excited_states_1_to_5"][0]
    require(abs(row["low_state_parities"][0] - 1.0) < 1e-10, f"L={length}: ground parity")
    require(abs(row["low_state_parities"][1] + 1.0) < 1e-10, f"L={length}: first parity")
    require(weights[0] < 1e-20, f"L={length}: X is not parity blind")
    require(weights[1] > 0.3, f"L={length}: Z lost visibility")
    windows = row["finite_window"]
    require(windows[1]["block_false_gap_localizer_min"] < 0.0, f"L={length}: no degree-1 block witness")
    require(all(w["x_only_false_gap_localizer_min"] >= -1e-13 for w in windows), f"L={length}: X witnesses")
    require(abs(windows[-1]["block_ritz"] - row["true_transfer_edge"]) < 6e-5, f"L={length}: Ritz error")


def main() -> None:
    check_exact_artifacts()

    local = load("annni_local_results.json")
    local_rows = local["results"]
    require([row["length"] for row in local_rows] == [6, 8, 10, 12], "local sizes changed")
    for row in local_rows:
        check_run(row, large=False)

    colab = load("colab_run_summary.json")
    require(colab["execution_surface"] == "Google Colab Pro+", "wrong execution surface")
    require(len(colab["full_result_sha256"]) == 64, "malformed result digest")
    large_rows = colab["summary"]
    require([row["L"] for row in large_rows] == [12, 14, 16], "Colab sizes changed")
    for row in large_rows:
        check_run(row, large=True)

    print("verified: exact recovery, hidden-atom no-go, Chebyshev bound, and ANNNI L=6..16")


if __name__ == "__main__":
    main()
